#!/usr/bin/env python3
"""
Load the three Cypher files generated by catalogue_scan.py into Neo4j
via the Bolt protocol.  Batches each file into small transactions to
stay responsive.
"""
from __future__ import annotations

import sys
from pathlib import Path
from neo4j import GraphDatabase

URI = 'bolt://localhost:7687'
USER = 'neo4j'
PASSWORD = 'omegatheory2026'
ROOT = Path('/mnt/c/Users/Norbert/IdeaProjects/chaos-shield/PhysicsPapers/LeanFormalizationV2/.neo4j')

FILES = [
    'catalogue_files.cypher',
    'catalogue_declarations.cypher',
    'catalogue_imports.cypher',
]

# Batch size for streaming Cypher into Neo4j
BATCH = 50


def split_statements(text: str) -> list[str]:
    """Split a Cypher script into individual statements at ';\\n' boundaries."""
    stmts = []
    buf = []
    for line in text.splitlines():
        s = line.strip()
        if not s or s.startswith('//'):
            continue
        buf.append(line)
        if s.endswith(';'):
            stmts.append('\n'.join(buf).rstrip(';').strip())
            buf = []
    if buf:
        remainder = '\n'.join(buf).strip()
        if remainder:
            stmts.append(remainder)
    return stmts


def run_file(driver, path: Path):
    text = path.read_text(encoding='utf-8')
    statements = split_statements(text)
    print(f'[{path.name}] {len(statements)} statements')
    n = 0
    with driver.session() as session:
        batch = []
        for stmt in statements:
            if stmt.upper().startswith('RETURN '):
                continue  # skip trailing status returns
            batch.append(stmt)
            if len(batch) >= BATCH:
                tx = session.begin_transaction()
                for s in batch:
                    tx.run(s)
                tx.commit()
                n += len(batch)
                batch = []
                if n % 500 == 0:
                    print(f'  {n} done')
        if batch:
            tx = session.begin_transaction()
            for s in batch:
                tx.run(s)
            tx.commit()
            n += len(batch)
    print(f'  total executed: {n}')


def stats(driver):
    with driver.session() as session:
        q = """
        MATCH (n) WHERE n.namespace = 'OmegaTheoryV2'
        RETURN labels(n)[0] AS label, count(n) AS count
        ORDER BY count DESC
        """
        print('\nNode counts for OmegaTheoryV2:')
        for rec in session.run(q):
            print(f'  {rec["label"]:20s} {rec["count"]}')

        q2 = """
        MATCH (a {namespace:'OmegaTheoryV2'})-[r]->(b {namespace:'OmegaTheoryV2'})
        RETURN type(r) AS rel, count(*) AS count
        ORDER BY count DESC
        """
        print('\nRelationship counts:')
        for rec in session.run(q2):
            print(f'  {rec["rel"]:25s} {rec["count"]}')


def main():
    driver = GraphDatabase.driver(URI, auth=(USER, PASSWORD))
    try:
        driver.verify_connectivity()
        print('Connected to Neo4j')
        for fn in FILES:
            run_file(driver, ROOT / fn)
        stats(driver)
    finally:
        driver.close()


if __name__ == '__main__':
    main()
