/-
  OmegaTheory.Foundations.FiniteAFAlgebraSquaredNorm

  **Lion's-Pride Phase 6.5n (2026-05-06)**:
  *Finite Chamseddine-Connes A_F algebra SQUARED-NORM function at
  c_part — defines `‖a‖²|c = a.c_part.1² + a.c_part.2²` (the
  standard ℝ²-Euclidean / ℂ-modulus squared on the ℂ-component) and
  proves the canonical norm properties: non-negativity, zero/one
  normalization, ℝ-scalar quadratic homogeneity, and adjoint
  invariance. Foundation for the future definition of `IsUnitary a`
  via `‖a‖² = 1` at appropriate components.*

  ## Why this file

  In Connes' framework the gauge group of a spectral triple is
  extracted as `Inn(A_F) / Z(A_F)` where `Inn(A_F)` is generated by
  unitary elements `u` satisfying `u* · u = 1` (i.e., `‖u‖² = 1`
  in the canonical norm).

  This file ships the SQUARED-NORM function on the c_part field,
  the foundation step before introducing `IsUnitary` in a future
  iteration.  Component-wise, the c_part is `ℂ ≅ ℝ × ℝ`, and the
  natural norm is the standard Euclidean modulus.

  ## What this file ships

  | Property                                              | Theorem                                              |
  |-------------------------------------------------------|------------------------------------------------------|
  | `cPartSquaredNorm`                                    | (def — `a.c_part.1² + a.c_part.2²`)                  |
  | `cPartSquaredNorm_nonneg`                             | 0 ≤ ‖a‖²                                             |
  | `cPartSquaredNorm_zero`                               | ‖0‖² = 0                                             |
  | `cPartSquaredNorm_one`                                | ‖1‖² = 1                                             |
  | `cPartSquaredNorm_smul`                               | ‖r • a‖² = r² · ‖a‖²                                 |
  | `cPartSquaredNorm_adj`                                | ‖adj a‖² = ‖a‖²                                      |
  | Headline (5-conjunct)                                 | `finite_AF_algebra_squared_norm_report`              |

  ## Author

  Lion's-Pride dynamic /loop iteration 124 (2026-05-06).
  Single-thread Opus 4.7 [1M context], no mass wizards.

  Rule 1: zero `sorry`.  Rule 2: zero new axioms (Lean core only).
-/

import OmegaTheory.Foundations.FiniteAFAlgebra
import OmegaTheory.Foundations.FiniteAFAlgebraMul
import OmegaTheory.Foundations.FiniteAFAlgebraAdjoint
import OmegaTheory.Foundations.FiniteAFAlgebraSMul
import Mathlib.Tactic
import Mathlib.Data.Real.Basic

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option linter.style.show false

namespace OmegaTheory.Foundations.FiniteAFAlgebraSquaredNorm

open OmegaTheory.Foundations.FiniteAFAlgebra
open OmegaTheory.Foundations.FiniteAFAlgebraMul
open OmegaTheory.Foundations.FiniteAFAlgebraAdjoint
open OmegaTheory.Foundations.FiniteAFAlgebraSMul

/-! ## 1. The squared-norm at c_part -/

/-- **c_part squared-norm**:
    `‖a‖²|c := a.c_part.1² + a.c_part.2²`.

    This is the standard ℝ²-Euclidean / ℂ-modulus squared on the
    ℂ-component of A_F = ℂ ⊕ ℍ ⊕ M_3(ℂ). -/
def cPartSquaredNorm (a : FiniteAFAlgebra) : ℝ :=
  a.c_part.1^2 + a.c_part.2^2

/-! ## 2. Non-negativity and zero/one normalization -/

/-- **Squared-norm at c_part is non-negative**:
    `0 ≤ ‖a‖²|c`. -/
theorem cPartSquaredNorm_nonneg (a : FiniteAFAlgebra) :
    0 ≤ cPartSquaredNorm a := by
  unfold cPartSquaredNorm
  positivity

/-- **Squared-norm of zero**: `‖0‖²|c = 0`. -/
theorem cPartSquaredNorm_zero :
    cPartSquaredNorm (0 : FiniteAFAlgebra) = 0 := by
  show (0 : ℝ)^2 + (0 : ℝ)^2 = 0
  ring

/-- **Squared-norm of one**: `‖1‖²|c = 1`. -/
theorem cPartSquaredNorm_one :
    cPartSquaredNorm (1 : FiniteAFAlgebra) = 1 := by
  show (1 : ℝ)^2 + (0 : ℝ)^2 = 1
  ring

/-! ## 3. ℝ-scalar quadratic homogeneity -/

/-- **Squared-norm scalar quadratic homogeneity**:
    `‖r • a‖²|c = r² · ‖a‖²|c`. -/
theorem cPartSquaredNorm_smul (r : ℝ) (a : FiniteAFAlgebra) :
    cPartSquaredNorm (r • a) = r^2 * cPartSquaredNorm a := by
  show (r * a.c_part.1)^2 + (r * a.c_part.2)^2 =
       r^2 * (a.c_part.1^2 + a.c_part.2^2)
  ring

/-! ## 4. Adjoint invariance -/

/-- **Squared-norm is adjoint-invariant at c_part**:
    `‖adj a‖²|c = ‖a‖²|c`.

    Reflects the standard fact that complex conjugation preserves
    the modulus: `|z*| = |z|`, hence `|z*|² = |z|²`. -/
theorem cPartSquaredNorm_adj (a : FiniteAFAlgebra) :
    cPartSquaredNorm (adj a) = cPartSquaredNorm a := by
  show (a.c_part.1)^2 + (-a.c_part.2)^2 = a.c_part.1^2 + a.c_part.2^2
  ring

/-! ## 5. Headline composite report -/

/-- **Lion's-Pride Phase 6.5n headline — finite Chamseddine-Connes
    A_F algebra squared-norm structural report at c_part.**

    For any scalar `r : ℝ` and any element `a : FiniteAFAlgebra`:

    1. **Non-negativity**:
       `0 ≤ ‖a‖²|c`.

    2. **Zero normalization**:
       `‖0‖²|c = 0`.

    3. **One normalization**:
       `‖1‖²|c = 1`.

    4. **Scalar quadratic homogeneity**:
       `‖r • a‖²|c = r² · ‖a‖²|c`.

    5. **Adjoint invariance**:
       `‖adj a‖²|c = ‖a‖²|c`. -/
theorem finite_AF_algebra_squared_norm_report (r : ℝ) (a : FiniteAFAlgebra) :
    0 ≤ cPartSquaredNorm a ∧
    cPartSquaredNorm (0 : FiniteAFAlgebra) = 0 ∧
    cPartSquaredNorm (1 : FiniteAFAlgebra) = 1 ∧
    cPartSquaredNorm (r • a) = r^2 * cPartSquaredNorm a ∧
    cPartSquaredNorm (adj a) = cPartSquaredNorm a := by
  refine ⟨?_, ?_, ?_, ?_, ?_⟩
  · exact cPartSquaredNorm_nonneg a
  · exact cPartSquaredNorm_zero
  · exact cPartSquaredNorm_one
  · exact cPartSquaredNorm_smul r a
  · exact cPartSquaredNorm_adj a

end OmegaTheory.Foundations.FiniteAFAlgebraSquaredNorm
