/-
  OmegaTheory.Irrationality.HermitePade.BridgeTheorem

  Bridge Theorem 4A.1 — structural constraints forced on a K₂-predictable
  real number α.  (π-opacity diary, Module 04A.)

  Informal statement (4A.1)
  -------------------------
  If a real number α is **K₂-predictable** (i.e., its base-b digit
  sequence is generated by a finite-state process), then α satisfies
  each of:

    (a)  the continued-fraction partial quotients a_n are bounded;
    (b)  the irrationality measure μ(α) = 2;
    (c)  the geometric-mean growth rate is finite;
    (d)  the digit frequencies in any base are rational numbers.

  Scope of this file
  ------------------
  Per task spec, we formalize clauses (d) and, as its enabling
  sub-lemma, (a).  We work with the cleanest Lean representation of a
  K₂-predictable sequence: an **eventually-periodic sequence**
  `u : ℕ → α` with offset `N₀` and period `T`.  This is precisely the
  output of a finite-state automaton over a fixed base.

  Lemmas
  ------
  • `eventually_periodic_bounded` — clause (a) sub-lemma: an
    eventually-periodic sequence of naturals is bounded.

  • `eventually_periodic_digit_frequency_rational` — clause (d): for
    any eventually-periodic sequence `u : ℕ → Fin b`, and any target
    digit `d : Fin b`, the finite-window frequency
    `#{n < N · T : u n = d} / (N · T)` stabilises to a rational number
    as N → ∞.  We state this in the precise `∃ q : ℚ, ∀ N, freq_at N = q`
    form (exact rationality for aligned windows), which is the content
    consumed by Theorem 4A.1 (d).

  Dependencies: Mathlib v4.29.  No sorries, no new axioms beyond
  Mathlib (`propext`, `Classical.choice`, `Quot.sound`).
-/

import Mathlib.Data.Nat.Periodic
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Data.Fintype.Card
import Mathlib.Data.Rat.Cast.Defs
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Ring

namespace OmegaTheory.Irrationality.HermitePade

open BigOperators Finset

/--
**Eventually periodic sequence.**  A sequence `u : ℕ → α` is
`EventuallyPeriodic N₀ T` if `u (n + T) = u n` for all `n ≥ N₀`.

For `N₀ = 0` this is strictly periodic.  The general case models
"ignore the first `N₀` transient terms, then the sequence loops
with period `T`".
-/
def EventuallyPeriodic {α : Type*} (u : ℕ → α) (N₀ T : ℕ) : Prop :=
  ∀ n : ℕ, N₀ ≤ n → u (n + T) = u n

/--
**Clause (a) — boundedness of an eventually periodic ℕ-valued sequence.**

If `u : ℕ → ℕ` is eventually periodic with offset `N₀` and period `T ≥ 1`,
then `u` is bounded: there exists `M : ℕ` with `u n ≤ M` for all `n`.

Proof.  The values `u 0, u 1, …, u (N₀ + T - 1)` form a finite set, and
every later value equals one of `u N₀, …, u (N₀ + T - 1)` by applying
the period relation.  Take `M := max_{i < N₀ + T} u i`.
-/
theorem eventually_periodic_bounded
    {u : ℕ → ℕ} {N₀ T : ℕ} (hT : 1 ≤ T)
    (hper : EventuallyPeriodic u N₀ T) :
    ∃ M : ℕ, ∀ n, u n ≤ M := by
  -- Define the finite "fundamental window" of length `N₀ + T`.
  let W : Finset ℕ := Finset.range (N₀ + T)
  -- Take the max of `u` over `W`.
  let M : ℕ := W.sup u
  refine ⟨M, ?_⟩
  intro n
  -- Reduce `n` to an index within `W` using the period relation.
  by_cases hlt : n < N₀ + T
  · -- Already in the window.
    have : n ∈ W := Finset.mem_range.mpr hlt
    exact Finset.le_sup this
  · -- Out of window: push back by multiples of `T` until inside.
    push_neg at hlt
    -- Define `k := (n - N₀) / T` and `r := (n - N₀) % T`.
    set m := n - N₀ with hm_def
    have hm : n = m + N₀ := by omega
    -- Decompose `m = q * T + r` with `r < T`.
    have hTpos : 0 < T := hT
    have hdiv : m = (m / T) * T + m % T := (Nat.div_add_mod m T).symm
    have hr_lt : m % T < T := Nat.mod_lt _ hTpos
    -- Target index inside the window: `N₀ + (m % T)`, which is `< N₀ + T`.
    set j := N₀ + m % T with hj_def
    have hj_mem : j ∈ W := by
      refine Finset.mem_range.mpr ?_
      have := hr_lt
      omega
    -- Show `u n = u j` by iterating the period `(m / T)` times.
    have huj : u n = u j := by
      -- Helper: for all q, `u (j + q * T) = u j`.
      have hstep : ∀ q : ℕ, u (j + q * T) = u j := by
        intro q
        induction q with
        | zero => simp
        | succ q ih =>
          have hge : N₀ ≤ j + q * T := by
            have : N₀ ≤ j := by unfold_let j; omega
            have hqT : 0 ≤ q * T := Nat.zero_le _
            omega
          have : u (j + q * T + T) = u (j + q * T) := hper _ hge
          calc u (j + (q + 1) * T)
              = u (j + q * T + T) := by ring_nf
            _ = u (j + q * T) := this
            _ = u j := ih
      -- `n = j + (m / T) * T`.
      have hn_eq : n = j + (m / T) * T := by
        unfold_let j
        have : m = (m / T) * T + m % T := hdiv
        omega
      rw [hn_eq]
      exact hstep (m / T)
    rw [huj]
    exact Finset.le_sup hj_mem

/--
**Clause (d) — rational digit frequency on period-aligned windows.**

Let `u : ℕ → Fin b` be an eventually-periodic digit sequence (in base
`b ≥ 1`) with offset `N₀` and period `T ≥ 1`, and let `d : Fin b` be a
fixed target digit.

Consider the window `{N₀, N₀+1, …, N₀ + N·T − 1}` — i.e., `N` full
periods starting right after the transient.  The frequency of `d` in
this window is **exactly** the rational number

   `c d / T`,  where  `c d := #{ i ∈ range T : u (N₀ + i) = d }`,

independent of `N ≥ 1`.  Thus the frequency is rational and stable.

Proof.  Split the window into `N` consecutive blocks of length `T`;
by periodicity every block has the same count of `d`, namely `c d`.
Hence the total count is `N · c d` and the frequency is `N · c d /
(N · T) = c d / T`.
-/
theorem eventually_periodic_digit_frequency_rational
    {b : ℕ} {u : ℕ → Fin b} {N₀ T : ℕ} (hT : 1 ≤ T)
    (hper : EventuallyPeriodic u N₀ T) (d : Fin b) :
    ∃ q : ℚ, ∀ N : ℕ, 1 ≤ N →
      ((((Finset.range (N * T)).filter (fun i => u (N₀ + i) = d)).card : ℚ)
        / ((N * T : ℕ) : ℚ)) = q := by
  -- Per-period count:
  let c : ℕ := ((Finset.range T).filter (fun i => u (N₀ + i) = d)).card
  refine ⟨(c : ℚ) / (T : ℚ), ?_⟩
  intro N hN
  -- Step 1: show the window count is `N * c`.
  have hcount :
      ((Finset.range (N * T)).filter (fun i => u (N₀ + i) = d)).card
        = N * c := by
    -- Express `range (N * T)` as a disjoint union of `N` shifted blocks,
    -- each of length `T`, and show each block contributes exactly `c`.
    have hblock : ∀ k : ℕ, k < N →
        ((Finset.range T).filter
          (fun i => u (N₀ + (k * T + i)) = d)).card = c := by
      intro k _
      -- By periodicity: `u (N₀ + (k*T + i)) = u (N₀ + i)` for i < T, k ≥ 0.
      have hshift : ∀ i : ℕ, i < T →
          u (N₀ + (k * T + i)) = u (N₀ + i) := by
        intro i _
        -- Iterate the period `k` times: `u (N₀ + i + k * T) = u (N₀ + i)`.
        have hstep : ∀ q : ℕ, u (N₀ + i + q * T) = u (N₀ + i) := by
          intro q
          induction q with
          | zero => simp
          | succ q ih =>
            have hge : N₀ ≤ N₀ + i + q * T := by omega
            have h1 : u (N₀ + i + q * T + T) = u (N₀ + i + q * T) :=
              hper _ hge
            calc u (N₀ + i + (q + 1) * T)
                = u (N₀ + i + q * T + T) := by ring_nf
              _ = u (N₀ + i + q * T) := h1
              _ = u (N₀ + i) := ih
        have := hstep k
        have heq : N₀ + (k * T + i) = N₀ + i + k * T := by ring
        rw [heq]
        exact this
      -- Thus the filter predicate equals the original `c`-predicate on range T.
      refine Finset.card_bij (fun i _ => i) ?_ ?_ ?_
      · intro i hi
        rcases Finset.mem_filter.mp hi with ⟨hrange, hpred⟩
        have hilt : i < T := Finset.mem_range.mp hrange
        refine Finset.mem_filter.mpr ⟨hrange, ?_⟩
        rw [hshift i hilt] at hpred
        exact hpred
      · intro i _ j _ h
        exact h
      · intro i hi
        refine ⟨i, ?_, rfl⟩
        rcases Finset.mem_filter.mp hi with ⟨hrange, hpred⟩
        have hilt : i < T := Finset.mem_range.mp hrange
        refine Finset.mem_filter.mpr ⟨hrange, ?_⟩
        rw [hshift i hilt]
        exact hpred
    -- Step 2: sum block counts via a disjoint-union argument.
    -- We use `Finset.range (N * T) = ⋃ k < N, (k*T) + range T`.
    classical
    have hrange_split :
        Finset.range (N * T)
          = (Finset.range N).biUnion (fun k =>
              (Finset.range T).image (fun i => k * T + i)) := by
      ext n
      simp only [Finset.mem_range, Finset.mem_biUnion, Finset.mem_image,
                 Finset.mem_range]
      constructor
      · intro hn
        refine ⟨n / T, ?_, n % T, ?_, ?_⟩
        · exact Nat.div_lt_iff_lt_mul hT |>.mpr (by rw [Nat.mul_comm]; exact hn)
        · exact Nat.mod_lt _ hT
        · have := (Nat.div_add_mod n T)
          omega
      · rintro ⟨k, hkN, i, hiT, rfl⟩
        have : k * T + i < N * T := by
          have : k * T + i < k * T + T := by omega
          have hk : (k + 1) * T ≤ N * T :=
            Nat.mul_le_mul_right T (by omega)
          have hkT : k * T + T = (k + 1) * T := by ring
          omega
        exact this
    -- Pairwise disjointness of the blocks.
    have hdisj :
        ∀ k ∈ Finset.range N, ∀ k' ∈ Finset.range N, k ≠ k' →
          Disjoint
            ((Finset.range T).image (fun i => k * T + i))
            ((Finset.range T).image (fun i => k' * T + i)) := by
      intro k _ k' _ hkk
      rw [Finset.disjoint_left]
      intro x hx hx'
      rcases Finset.mem_image.mp hx with ⟨i, hi, rfl⟩
      rcases Finset.mem_image.mp hx' with ⟨j, hj, hij⟩
      have hiT : i < T := Finset.mem_range.mp hi
      have hjT : j < T := Finset.mem_range.mp hj
      -- From `k * T + i = k' * T + j` and `i,j < T`, get `k = k' ∧ i = j`.
      have : k = k' := by
        -- Divide both sides by T (integer).
        have h1 : (k * T + i) / T = k := by
          rw [Nat.add_mul_div_left _ _ hT]
          rw [Nat.mul_comm]
          simp [Nat.div_eq_of_lt hiT]
        have h2 : (k' * T + j) / T = k' := by
          rw [Nat.add_mul_div_left _ _ hT]
          rw [Nat.mul_comm]
          simp [Nat.div_eq_of_lt hjT]
        rw [hij] at h1
        rw [h2] at h1
        exact h1
      exact hkk this
    -- Rewrite the filtered-range card as a sum of block cards.
    rw [hrange_split]
    rw [Finset.filter_biUnion]
    rw [Finset.card_biUnion]
    · -- Each block contributes `c`.
      have hsum :
          ∑ k ∈ Finset.range N,
              ((((Finset.range T).image (fun i => k * T + i)).filter
                (fun i => u (N₀ + i) = d)).card)
            = ∑ _k ∈ Finset.range N, c := by
        apply Finset.sum_congr rfl
        intro k hk
        have hkN : k < N := Finset.mem_range.mp hk
        -- Rewrite filter over image as image of filter.
        have himg_filter :
            (((Finset.range T).image (fun i => k * T + i)).filter
                (fun n => u (N₀ + n) = d))
            =
            ((Finset.range T).filter
                (fun i => u (N₀ + (k * T + i)) = d)).image
              (fun i => k * T + i) := by
          ext n
          simp only [Finset.mem_filter, Finset.mem_image, Finset.mem_range]
          constructor
          · rintro ⟨⟨i, hi, rfl⟩, hpred⟩
            exact ⟨i, ⟨hi, hpred⟩, rfl⟩
          · rintro ⟨i, ⟨hi, hpred⟩, rfl⟩
            exact ⟨⟨i, hi, rfl⟩, hpred⟩
        rw [himg_filter]
        -- Card of image of injective map = card.
        rw [Finset.card_image_of_injective _ (fun i j hij => by
          have : k * T + i = k * T + j := hij
          omega)]
        exact hblock k hkN
      rw [hsum]
      simp [Finset.sum_const, Finset.card_range, Nat.mul_comm]
    · -- Disjointness of the filtered blocks.
      intro k hk k' hk' hkk
      exact (hdisj k hk k' hk' hkk).mono
        (Finset.filter_subset _ _) (Finset.filter_subset _ _)
  -- Step 3: conclude.
  rw [hcount]
  have hTpos : (0 : ℚ) < (T : ℚ) := by exact_mod_cast (Nat.lt_of_lt_of_le Nat.zero_lt_one hT)
  have hNpos : (0 : ℚ) < (N : ℚ) := by exact_mod_cast (Nat.lt_of_lt_of_le Nat.zero_lt_one hN)
  field_simp
  push_cast
  ring

/--
**Bridge Theorem 4A.1 (scoped clauses a + d).**

Packaging lemma: an eventually-periodic digit sequence in base `b`
with offset `N₀` and period `T ≥ 1` satisfies:

 • (a) digit values are bounded: `∃ M, ∀ n, (u n : ℕ) ≤ M`
       (trivially true since `u n : Fin b` has value `< b`, but we
       record the stronger Finset-sup bound for the "finite-state
       output is bounded" reading of clause (a)).

 • (d) for every target digit `d`, the frequency of `d` on period-
       aligned windows stabilises to a rational number.

These are the two clauses of 4A.1 that do not require the
continued-fraction / Liouville / measure-theoretic machinery.
-/
theorem bridge_theorem_4A1_ad
    {b : ℕ} {u : ℕ → Fin b} {N₀ T : ℕ} (hT : 1 ≤ T)
    (hper : EventuallyPeriodic u N₀ T) :
    (∃ M : ℕ, ∀ n, (u n : ℕ) ≤ M) ∧
    (∀ d : Fin b, ∃ q : ℚ, ∀ N : ℕ, 1 ≤ N →
      ((((Finset.range (N * T)).filter (fun i => u (N₀ + i) = d)).card : ℚ)
        / ((N * T : ℕ) : ℚ)) = q) := by
  refine ⟨?_, ?_⟩
  · -- Apply boundedness to the ℕ-projection of `u`.
    exact eventually_periodic_bounded hT
      (u := fun n => (u n : ℕ)) (fun n hn => by
        have := hper n hn
        rw [this])
  · intro d
    exact eventually_periodic_digit_frequency_rational hT hper d

/-!
### Axiom audit
-/
#print axioms eventually_periodic_bounded
#print axioms eventually_periodic_digit_frequency_rational
#print axioms bridge_theorem_4A1_ad

end OmegaTheory.Irrationality.HermitePade
