/-
  OmegaTheory.Irrationality.CustomMath.T5_Phase3_IsAlgebraicClosure

  T-5 (Roth's theorem axiom retirement) — Phase 3 sub session 130.
  IsAlgebraic closure properties (add, mul).

  Single-thread hand-authored 2026-04-27 (cycle 65).

  ## What this file delivers

  Re-exports of Mathlib's `IsAlgebraic` closure properties:

  1. **`T5_isAlgebraic_add`** : sum of two algebraic numbers is algebraic.
  2. **`T5_isAlgebraic_mul`** : product of two algebraic numbers is algebraic.

  Used in T-5 polynomial-index calculus where we work with field
  extensions generated by algebraic α and need closure properties.

  ## Project hard rules

  Per project HARD RULES — 0 sorry, 0 new axioms, GREEN build, NO STUBS.
-/

import Mathlib.RingTheory.Algebraic.Integral

namespace OmegaTheory.Irrationality.CustomMath.T5_Phase3_IsAlgebraicClosure

variable {R S : Type*} [CommRing R] [CommRing S] [Algebra R S] [NoZeroDivisors R]

/-! ## IsAlgebraic closure -/

/-- **Wave T5 session 130 — IsAlgebraic closed under sum**.

    `a, b algebraic over R  →  a + b algebraic over R`. -/
theorem T5_isAlgebraic_add {a b : S}
    (ha : IsAlgebraic R a) (hb : IsAlgebraic R b) :
    IsAlgebraic R (a + b) :=
  ha.add hb

/-- **Wave T5 session 130 — IsAlgebraic closed under product**.

    `a, b algebraic over R  →  a * b algebraic over R`. -/
theorem T5_isAlgebraic_mul {a b : S}
    (ha : IsAlgebraic R a) (hb : IsAlgebraic R b) :
    IsAlgebraic R (a * b) :=
  ha.mul hb

/-! ## Headline -/

/-- **HEADLINE — Wave T5 session 130 — IsAlgebraic closure**.

    Two foundational closure properties:
    1. Sum of algebraic numbers is algebraic.
    2. Product of algebraic numbers is algebraic.

    Sub-lemma 19/N in T-5 Phase 3.  Lean-core only.

    Used in T-5 polynomial-index calculus where we work with field
    extensions generated by algebraic α — closure under +/· keeps
    the algebraic structure intact. -/
theorem session_130_is_algebraic_closure_headline
    {R S : Type*} [CommRing R] [CommRing S] [Algebra R S] [NoZeroDivisors R] :
    -- (1) add
    (∀ {a b : S}, IsAlgebraic R a → IsAlgebraic R b → IsAlgebraic R (a + b))
    -- (2) mul
    ∧ (∀ {a b : S}, IsAlgebraic R a → IsAlgebraic R b → IsAlgebraic R (a * b)) :=
  ⟨T5_isAlgebraic_add, T5_isAlgebraic_mul⟩

end OmegaTheory.Irrationality.CustomMath.T5_Phase3_IsAlgebraicClosure
